### ISSUE TITLE
Create a basic project

### ISSUE THREAD

**Issue by parzival3** [johannesmols/MBSE-Project-Group-7#2]

**Comment by parzival3** [comment]
@johannesmols oi I've seen your work with Github actions it doesn't work? Do we need a license for Unity to do CI?

**Comment by johannesmols** [comment]
@parzival3 I'm not sure what the issue was to be honest. I tried several different template projects but they all failed for different reasons and the documentation is not very good. After trying around for a while I decided it's not worth it. You're welcome to see if you can make it work though.

**Comment by parzival3** [comment]
Ok I'll give it a shot tomorrow :muscle: , thanks for the template :+1:
